### ISSUE TITLE
API key is Open to Public

### ISSUE THREAD

**Issue by TheSeer507** [distbit0/langchainExperiments#2]
Issue: API Key is open in plain text
Severity: High
Reason: Plain Text API key enables unauthorized actors to use the Key and rack up cost in your account 
Solution: Create a .env file and add it to .gitignore, on the .env file add your API key so it isnt loaded on the main source code

.env file 
OPENAI_API_KEY = 'Your API key"

Calling the .env on your code:
`pip install python-dotenv`

`from dotenv import load_dotenv
import os`

`load_dotenv()  # take environment variables from .env.
API_KEY = os.getenv('API_KEY')`

`print(API_KEY)  # just for checking; remove it in your actual code`

**Comment by distbit0** [comment]
Thx yeah openai detected this when I committed it, and de-activated the api key automatically. :) Will close this issue now.
